apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
      - name: pingapp
        image: nicopaez/pingapp:2.1.0
        envFrom:
          - configMapRef:
              name: configmap1
        volumeMounts:
          - name: configmap-volume
            mountPath: /mydata
          - name: secrets-volume
            mountPath: /mysecrets
      volumes:
        - name: configmap-volume
          configMap:
            name: "configmap2"
            items:
            - key: "config.json"
              path: "config.json"
        - name: secrets-volume
          secret:
            secretName: pingapp-secret