version: '3.9'
services:
  websrv1:
    image: nicopaez/password-api

  websrv2:
    image: nicopaez/password-api

  balancer:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - websrv1
      - websrv2
    ports:
      - "8080:8080"
    depends_on:
      - websrv1
      - websrv2
